config/routes.rb
Uuarch::Application.routes.draw do
  
  get "profiles/show"

  devise_for :users

  devise_scope :user do
    get 'register', :to => 'devise/registrations#new', as: :register
    get 'login', :to => 'devise/sessions#new', as: :login
    get 'logout', :to => 'devise/sessions#destroy', as: :logout
  end

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/home', to: 'static_pages#home'

  resources :steps
  resources :tasks do
    resources :steps
  end
  
  root :to => 'tasks#index'

  get '/:id', to: 'profiles#show'

end

app/models/document.rb
class Document < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :task
  attr_accessible :description, :file_url, :image_url, :name
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
  has_many :steps

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :full_name

  validates :full_name, presence: true,
                        uniqueness: true
                        
  # attr_accessible :title, :body
  has_many :tasks
  
  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_full_name(params[:id])
    if @user
      @tasks = @user.tasks.all
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  def edit
    @task = Task.find(params[:task_id])
    @step = @task.steps.find(params[:id])
  end
 
  def update 
    @step = Step.find(params[:id])

    if @step.update_attributes(params[:step])
	     redirect_to task_path(@step.task)
    else 
	render 'edit'
    end
  end

  def create
    @task = Task.find(params[:task_id])
    @step = @task.steps.create(params[:step])
    redirect_to task_path(@task)
  end
 
  def destroy
    @task = Task.find(params[:task_id])
    @step = @task.steps.find(params[:id])
    @step.destroy
    redirect_to task_path(@task)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
  def flash_class(type)
    case type
    when :alert
         "alert-error"
    when :notice
         "alert-success"
    else 
         ""
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uuarch | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a href="#" class="brand"> UUARCH</a>
				<ul class="nav">
					<li><%= link_to "学习", tasks_path %></li>
					</ul>
                    <ul class="nav pull-right">
                       <% if user_signed_in? %>
                             <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
                             <li><%= link_to "退出", logout_path %></li>
                       <% else %>
                             <li><%= link_to "注册", register_path %></li>
                             <li><%= link_to "登录", login_path %></li>
                      <% end %>
                    </ul>
			</div>
		</div>
	</div>


	<div class="container">

      <% flash.each do |type, message| %>
           <div class="alert <%= flash_class type %>">
              <button class="close" data-dismiss="alert">x</button>
              <%= message %>
           </div>
       <% end %>
           
    		<%= yield %>
	</div>



</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name %></h1>
</div>

<% if @tasks %>
  <% @tasks.each do |task| %>
    <div class="well">
      <%= task.name %>
    </div>
  <% end %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  UUARCH Opensource Design is made by Binxia from UUARCH INC.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on UUARCH Opensource Design, please contact uuarch@126.com.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>UUARCH</h1>
<p>
  This is the home page for the UUARCH Opensource Design.
</p>

app/views/steps/_form.html.erb
<%= simple_form_for([@task, @task.steps.build],html: {class: "form-horizontal"}) do |f| %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :image_url %>
  <%= f.input :file_url %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/steps/_selfform.html.erb
<%= simple_form_for(@step,html: {class: "form-horizontal"}) do |f| %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :image_url %>
  <%= f.input :file_url %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/steps/_step.html.erb
  <p>
    <b>Name:</b>
    <%= step.name %>
  </p>
 
  <p>
    <b>Description:</b>
    <%= step.description %>
  </p>

  <p>
    <b>Image:</b>
    <%= step.image_url %>
  </p>

  <p>
    <b>File:</b>
    <%= step.file_url %>
  </p>

  <p>
	<%= link_to 'Edit step',  edit_task_step_path(@task, step) %>
  </p>

  <p>
    <%= link_to 'Destroy Step', [step.task, step],
               :confirm => 'Are you sure?',
               :method => :delete %>
  </p>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'selfform' %>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, html: {class: "form-horizontal"}) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="page-header">
  <h1>所有任务</h1>
</div>

<% @tasks.each do |task| %>
<div class="task">
  <div class="row">

    <div class="span7">
      <p><%= task.name %></p>
      <div class="meta">
        <%= link_to "显示", task %>
        <span class="admin">
          | <%= link_to "编辑", edit_task_path(task) %> |
          <%= link_to "删除", task, method: :delete, data: { confirm: "Are you sure you want to delete this task?"} %>
        <span>
      </div>
    </div>
  </div>
</div>
<% end %>

<%= link_to "创建新任务", new_task_path, class: "btn btn-success" %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @task.user.full_name %>
</p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<h2>Steps</h2>
<%= render @task.steps %>

<h2>Add a step:</h2>
<%= render "steps/form" %>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>